### ISSUE TITLE
Bug: The first arg cannot be a promise

### ISSUE THREAD

**Issue by zhaoyao91** [coderaiser/try-to-catch#1]
due to this check: 

https://github.com/coderaiser/try-to-catch/blob/master/lib/try-to-catch.js#L9

the first arg cannot be a promise. this is not consistent with the first example in the README

**Comment by coderaiser** [comment]
You are right, thank you 🙂. `try-to-catch` is mostly about `async`-functions, or functions that will return promise, but not about already created promise.
