### ISSUE TITLE
Infinity returns null error

### ISSUE THREAD

**Issue by goxr3plus** [coderaiser/try-to-catch#2]
Well i just found this library and i have two question :) .

1) try-to-catch error for `Infinity` returns null.

```
try{
 console.log(10/0)
}catch(error){
 console.log(error)
}
```

When i do `try-to-catch` with `console.log(10/0)` it returns `[null,null]`

2) How can i execute an function if there is an error :) ?

**Comment by coderaiser** [comment]
The thing is `10/0` doesn't provide an exception, because formally it's not error :). If you want to caught exception, you should throw it first :):

```js
try {
   console.log(`that's ok: ${10/0}`);
   throw Error('Infinity should throw!');
} catch(error) {
 console.log(`This is an error ${error.message}`);
}
```

And this will return an `error` as first element of `try-to-catch` calling result.

**Comment by goxr3plus** [comment]
Hm that's really interesting.
