### ISSUE TITLE
TypeScript Types: Add `@types/try-to-catch` package on Definitely Typed

### ISSUE THREAD

**Issue by karlhorky** [coderaiser/try-to-catch#3]
First of all, thanks for this package, really useful! Nice to be able to work in a more functional way.

I wanted to ask what your opinion was on including TypeScript types in this package?

**Comment by karlhorky** [comment]
If you're not up for that, then an alternative would be to submit a new `@types/try-to-catch` package to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by karlhorky** [comment]
In case anyone is looking, here are some quick types I wrote (I added them temporarily to a file called `try-to-catch.d.ts` in the root of my project):

```ts
declare module 'try-to-catch' {
  export = tryToCatch;
}
 
declare function tryToCatch<T>(
  fn: (...args: any[]) => Promise<T>,
  ...fnArgs: any[]
): Promise<[Error | null, T]>;
 
declare function tryToCatch<U>(
  fn: (...args: any[]) => U,
  ...fnArgs: any[]
): Promise<[Error | null, U]>;
```

**Comment by coderaiser** [comment]
Could you please add PR to `DefinitelyTyped` (with link to this issue), I think it will be very useful :).

**Comment by karlhorky** [comment]
Here's a better version, with improved return types, a generic for the function arguments, and better names for the generics:

```typescript
declare function tryToCatch<PromiseData, FnArgs extends any[]>(
  fn: (...args: FnArgs) => Promise<PromiseData>,
  ...fnArgs: FnArgs
): Promise<[Error] | [null, PromiseData]>;

declare function tryToCatch<Data, FnArgs extends any[]>(
  fn: (...args: FnArgs) => Data,
  ...fnArgs: FnArgs
): Promise<[Error] | [null, Data]>;
```

I may be able to get around to doing a proper PR on DT, but if someone else does it, that would be good too :)

**Comment by LinqLover** [comment]
@karlhorky This definition is still not perfect IMHO. I use the utility like this

```ts
const [error, result] = await tryToCatch(() => 2 + 3)
if (error) {
    console.log("Error!")
} else {
    console.log(result + 1)
}
```

but am getting a type error from the `result + 1` part because `result` is `number | undefined`. Is it possible to add a proper type guard to the declaration so that TypeScript can know that `result` is not `undefined` because `error` was not `null`?

**Comment by karlhorky** [comment]
@LinqLover TypeScript 4.4 (to be released soon-ish) will be able to do this: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-rc/#cfa-aliased-conditions

**Comment by LinqLover** [comment]
Ah, so we need to wait until then?

**Comment by karlhorky** [comment]
hehe looks like it's out! https://www.npmjs.com/package/typescript

<img width="361" alt="Screen Shot 2021-08-27 at 08 31 44" src="https://user-images.githubusercontent.com/1935696/131082699-4c957806-1a5f-4a32-a828-b700960b8cbc.png">

**Comment by karlhorky** [comment]
@LinqLover would you be available to do the PR to DefinitelyTyped? I don't think I will be personally able to get to this soon...

**Comment by LinqLover** [comment]
I'm afraid I'm not very proficient with these CFA guards, maybe later ...

But why would you send them to DefinitelyTyped? If @coderaiser is still reachable, we could also store the type defs right here, which would improve maintainability I guess.

**Comment by karlhorky** [comment]
> But why would you send them to DefinitelyTyped? If @coderaiser is still reachable, we could also store the type defs right here, which would improve maintainability I guess.

I agree about maintainability, but @coderaiser originally decided [above](https://github.com/coderaiser/try-to-catch/issues/3#issuecomment-756719953) to go with a PR to DefinitelyTyped instead:

> Could you please add PR to `DefinitelyTyped` (with link to this issue), I think it will be very useful :).

**Comment by karlhorky** [comment]
> I'm afraid I'm not very proficient with these CFA guards, maybe later ...

To be clear, I think that the types I posted [above](https://github.com/coderaiser/try-to-catch/issues/3#issuecomment-757348037) should probably work (you shouldn't need to write any new types code) - it's mainly just the work of getting the PR set up for DefinitelyTyped and writing a test.

**Comment by LinqLover** [comment]
Alright, it's on my never-ending to-do list, if no one else preempts me :)

**Comment by coderaiser** [comment]
Hi guys, I don't really use `TS`, so don't want to add types into package, anyways I created PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55283.

Could you please take a look?

**Comment by coderaiser** [comment]
@LinqLover @karlhorky could you please check is https://www.npmjs.com/package/@types/try-to-catch works for you? It just published :) 🎉

**Comment by karlhorky** [comment]
> > but am getting a type error from the `result + 1` part because `result` is `number | undefined`. Is it possible to add a proper type guard to the declaration so that TypeScript can know that `result` is not `undefined` because `error` was not `null`?
>
> @LinqLover TypeScript 4.4 (to be released soon-ish) will be able to do this: [devblogs.microsoft.com/typescript/announcing-typescript-4-4-rc/#cfa-aliased-conditions](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-rc/#cfa-aliased-conditions)

Actually, it appears that I'm wrong here. TypeScript 4.4 still forgets the relationship between the two variables as soon as destructuring happens:

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxgE8AVHAYSgzAAsAeABRhwFssBnEAESqgBp4AMVQBBGAHN28EAA8MIVMClRURANoBdAHwAKAFDwkqAFzwdAOkuxJp4WMkBKeAF4t8Jqw4hGzNpx4YUFp8BvCW5oiiEuy2UZJ6DqYeft5qAKIwzDAa8AA+8GqoyBAQAsleAVDaANx6eqCQsAgo6Nh4BMRklNT0lQJ20dJyCkrwKura+oaRphZW0bH27E6u8H2h4ZFLi9EJSb5edOmZONl5BUUlApU1dVDsROhmK24A3qFgeOwYBSCZAsBeDlnGMAO5QLA-QikChUWg6HQvMyvAAOzBRpgA5J9UPJcZiAL4OByhLCIMx-GBOd6GQw49g4CAgcwQHDiHSU8wsEDsdhQcQgJwAeiF8EAoOShAkfL6M5ms9mAwLmNE4FHC0WAGXI9ASgA

Eg. this still applies: https://stackoverflow.com/a/59786171/1268612

---

It looks like this is actually a separate feature request called "Correlated Unions" by jcalz here: https://github.com/microsoft/TypeScript/issues/30581

**Comment by coderaiser** [comment]
I'll close this, since we already have types in [@types/try-to-catch](https://www.npmjs.com/package/@types/try-to-catch) 🎉
